---

- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: MongoDB Install
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Ensure mongodb db data directory exists
  file:
    path:  "{{ mongodb_data_dir }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode:  0755
    state: directory

- name: Ensure mongodb log directory exists
  file:
    path:  "{{ mongodb_log_dir }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode:  0755
    state: directory

- name: Update mongodb config file
  template: 
    src:   mongod.conf.j2
    dest:  "{{ mongodb_conf_file }}"
    owner: root
    group: root
    mode:  0644
  notify: Restart mongodb

- name: Update mongodb defaults settings config file
  template: 
    src:   etc.default.mongod.j2
    dest:  /etc/default/mongod
    owner: root
    group: root
    mode:  0644
  when: mongodb_apply_defaults_settings and ansible_os_family|lower == 'debian'
  notify: Restart mongodb

- name: debian | Configuring MongoDB Service (Xenial)
  template:
    src: "etc/systemd/system/mongod.service.j2"
    dest: "/etc/systemd/system/mongod.service"
    owner: "root"
    group: "root"
    mode: 0644
  when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_release|lower == "xenial"

- name: Start mongodb (init)
  service: name=mongod enabled=yes state=started
  when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_release|lower == "trusty"

- name: Start mongodb (systemd)
  systemd: state=started name=mongod daemon_reload=yes
  when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_release|lower == "xenial"

- include: replica_set.yml
  when: mongodb_create_replica_set
